Catch case with zero input files.

diff --git a/DICOM_anonymization/internal/scripts/anonymize_partial b/DICOM_anonymization/internal/scripts/anonymize_partial
--- a/DICOM_anonymization/internal/scripts/anonymize_partial
+++ b/DICOM_anonymization/internal/scripts/anonymize_partial
@@ -89,6 +89,11 @@ if [ -z "$PatientIDProvided" ] \
     exit 1
 fi
 
+if [ -z "$(find "${thedir}" -maxdepth 1 -mindepth 1 -type f )" ] ; then
+    printf 'Cannot access any input files. Your filesystem may be unsupported. Refusing to proceed.\n' 1>&2
+    exit 1
+fi
+
 # A simple routine to generate (toy) UIDs.
 genericUID() {
     printf "1.2.54328975.${RANDOM}.${RANDOM}${RANDOM}.$(date +%Y%m%d.%-N)"
